"""empty message

Revision ID: 140df2d9abac
Revises: 
Create Date: 2023-03-14 00:02:01.082999

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '140df2d9abac'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profile__property',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Type', sa.String(length=300), nullable=True),
    sa.Column('Title_of_Property', sa.String(length=300), nullable=True),
    sa.Column('Number_of_Bedrooms', sa.Integer(), nullable=True),
    sa.Column('Number_of_Bathrooms', sa.Integer(), nullable=True),
    sa.Column('Locations', sa.String(length=300), nullable=True),
    sa.Column('Price', sa.Integer(), nullable=True),
    sa.Column('filename', sa.String(length=300), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('profile__property')
    # ### end Alembic commands ###
